### ISSUE TITLE
Enable CORS for tweets api

### ISSUE THREAD

**Issue by prasannamestha** [zernonia/tweetic#34]
Hello,
Currently cors headers are not returned for the `/api/tweets` endpoint. It would be great if you could add `Access-Control-Allow-Origin: *` headers to the same

Thanks

**Comment by prasannamestha** [comment]
I created a PR to enable cors across pages - but would be great if you could at least allow cors for the tweets api.

PR: https://github.com/zernonia/tweetic/pull/35

Thanks

**Comment by zernonia** [comment]
Should be upstream issue https://github.com/unjs/h3/issues/82
