### ISSUE TITLE
Support an API route which only returns the metadata of a specific tweet

### ISSUE THREAD

**Issue by Borrus-sudo** [zernonia/tweetic#37]
**Support an API route which only returns the metadata of a specific tweet**
I want an API route which allows me to fetch only the metadata of a tweet (not the rendered html), so the metadata can be utilized by a custom renderer.
Example :
```json
"meta": {
    "user_id": "4798109946",
    "name": "Zernonia",
    "screen_name": "zernonia",
    "verified": false,
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/1476010084295716864/xfN1G89G_normal.jpg",
    "url": "https://twitter.com/zernonia/status/1524620865987506176",
    "profile_url": "https://twitter.com/zernonia",
    "created_at": "2022-05-12T05:21:55.000Z",
    "favorite_count": 219,
    "conversation_count": 17,
    "tweet_body":"<THE BODY>"
  }
```
This metadata will be consumed by my custom renderer

**Comment by zernonia** [comment]
Hi @Borrus-sudo !

If you are only interested with the metadata, you can use fetch:
`https://cdn.syndication.twimg.com/tweet?id=${ tweetId }`
